name: Mirror to GitLab

on:
  push:
    branches:
      - "**"

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror repository
        env:
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
          GITLAB_REPO: git@gitlab.gwdg.de:l.keiser/sbcli.git
        run: |
          git clone --mirror "https://gitlab.gwdg.de/l.keiser/sbcli.git" repo
          cd repo
          git remote add gitlab "$GITLAB_REPO"
          git push --mirror gitlab
